import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { WalletProviderComponent } from './context/walletContext';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head>
        <meta property="og:image" content="/icon.png" />
        <meta property="dscvr:canvas:version" content="vNext" />
        <title>Proof of Presence</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <WalletProviderComponent>
          {children}
        </WalletProviderComponent>
      </body>
    </html>
  );
}
